qlib_init:
  provider_uri: "~/.qlib/qlib_data/cn_data"
  region: cn

market: &market csi300
benchmark: &benchmark SH000300

data_handler_config: &data_handler_config
    start_time: 2008-01-01
    # end_time: 2020-08-01
    end_time: 2024-12-31
    fit_start_time: 2008-01-01
    # fit_end_time: 2014-12-31
    fit_end_time: 2018-12-31
    instruments: *market
    infer_processors:
        - class: FilterCol
          kwargs:
              fields_group: feature
              col_list: ["RESI5", "WVMA5", "RSQR5", "KLEN", "RSQR10", "CORR5", "CORD5", "CORR10", 
                            "ROC60", "RESI10", "VSTD5", "RSQR60", "CORR60", "WVMA60", "STD5", 
                            "RSQR20", "CORD60", "CORD10", "CORR20", "KLOW"
                        ]
        - class: RobustZScoreNorm
          kwargs:
              fields_group: feature
              clip_outlier: true
        - class: Fillna
          kwargs:
              fields_group: feature
    learn_processors:
        - class: DropnaLabel
        - class: CSRankNorm
          kwargs:
              fields_group: label
    label: ["Ref($close, -2) / Ref($close, -1) - 1"] 

model_config: &model_config
  input_size: 158
  hidden_size: 256
  num_layers: 2
  num_heads: 2
  use_attn: True
  dropout: 0.1

num_states: &num_states 1

tra_config: &tra_config
  num_states: *num_states
  hidden_size: 16
  tau: 1.0
  src_info: LR_TPE

task:
  model:
    class: TRAModel
    module_path: src/model.py
    kwargs:
      lr: 0.0002
      n_epochs: 500
      max_steps_per_epoch: 100
      early_stop: 20
      seed: 1000
      logdir: output/test/alstm
      model_type: LSTM
      model_config: *model_config
      tra_config: *tra_config
      lamb: 1.0
      rho: 0.99
      freeze_model: False
      model_init_state: 
  dataset:
    class: MTSDatasetH
    module_path: src/dataset.py
    kwargs:
      handler:
        class: Alpha158
        module_path: qlib.contrib.data.handler
        kwargs: *data_handler_config
      segments:
        # train: [2007-10-30, 2016-05-27]
        # valid: [2016-09-26, 2018-05-29]
        # test: [2018-09-21, 2020-06-30]
        train: [2008-01-01, 2018-12-31]
        valid: [2019-01-01, 2021-12-31]
        test: [2022-01-01, 2024-12-31]
      seq_len: 60
      horizon: 21
      num_states: *num_states
      batch_size: 1024