qlib_init:
    provider_uri: "/home/v-yuanteli/RD-Agent/git_ignore_folder/quant_data"
    region: cn
market: &market csi500
benchmark: &benchmark SH000905

data_handler_config: &data_handler_config
    start_time: 2008-01-01
    end_time: 2025-06-30
    fit_start_time: 2008-01-01
    fit_end_time: 2021-12-31
    instruments: *market
    infer_processors:
        - class: FilterCol
          kwargs:
              fields_group: feature
              col_list: ["RESI5", "WVMA5", "RSQR5", "KLEN", "RSQR10", "CORR5", "CORD5", "CORR10", 
                            "ROC60", "RESI10", "VSTD5", "RSQR60", "CORR60", "WVMA60", "STD5", 
                            "RSQR20", "CORD60", "CORD10", "CORR20", "KLOW"
                        ]
        - class: RobustZScoreNorm
          kwargs:
              fields_group: feature
              clip_outlier: true
        - class: Fillna
          kwargs:
              fields_group: feature
    learn_processors:
        - class: DropnaLabel
        - class: CSRankNorm
          kwargs:
              fields_group: label
    label: ["Ref($close, -2) / Ref($close, -1) - 1"]
port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal: <PRED>
            topk: 50
            n_drop: 5
    backtest:
        start_time: 2024-01-01
        end_time: 2025-06-30
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: 0.095
            deal_price: close
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5

task:
    model:
        class: PatchTST
        module_path: model.patchtst
        kwargs:
            d_feat: 20  # 特征维度，通常设置为输入特征的维度，范围[10-100]
            seq_len: 20  # 输入序列长度，表示使用多少历史数据点，范围[10-100]
            pred_len: 1  # 预测长度，表示预测未来多少个时间点，范围[1-30]
            dropout: 0.0  # 模型dropout率，用于防止过拟合，范围[0.0-0.5]
            batch_size: 800  # 批次大小，根据GPU内存调整，范围[32-1024]
            epoch: 15  # 训练轮数，范围[10-100]
            early_stop: 3  # 早停轮数，当验证集性能不再提升时停止训练，范围[3-10]
            optimizer: adam  # 优化器选择，可选[adam, sgd]
            loss: mse  # 损失函数，可选[mse, mae]
            metric: loss  # 评估指标，可选[loss, mse, mae]
            lr: 0.00001  # 学习率，范围[0.00001-0.001]
            enc_in: 20  # 编码器输入维度，通常等于d_feat，范围[10-100]
            dec_in: 1  # 解码器输入维度，通常等于预测目标维度，范围[1-10]
            d_model: 256  # Transformer模型维度，范围[32-512]
            d_ff: 1024  # 前馈网络维度，通常为d_model的4倍，范围[128-2048]
            n_heads: 4  # 注意力头数，通常为d_model的因子，范围[2-16]
            e_layers: 3  # 编码器层数，范围[1-6]
            d_layers: 2  # 解码器层数，范围[1-6]
            fc_dropout: 0.1  # 全连接层dropout率，范围[0.0-0.5]
            head_dropout: 0.1  # 注意力头dropout率，范围[0.0-0.5]
            norm: "batchnorm"  # 归一化方法，可选[batchnorm, layernorm]
            act: "gelu"  # 激活函数，可选[gelu, relu, leakyrelu]
            key_padding_mask: True  # 是否使用padding mask，布尔值
            padding_var: None  # padding变量，通常为None
            attn_mask: None  # 注意力mask，通常为None
            res_attention: True  # 是否使用残差注意力，布尔值
            pre_norm: False  # 是否使用预归一化，布尔值
            store_attn: False  # 是否存储注意力权重，布尔值
            pe: "zeros"  # 位置编码类型，可选[zeros, sinusoid]
            learn_pe: True  # 是否学习位置编码，布尔值
            pretrain_head: False  # 是否使用预训练头，布尔值
            head_type: "flatten"  # 头类型，可选[flatten, fc]
            individual: False  # 是否对每个特征单独处理，布尔值
            revin: False  # 是否使用RevIN，布尔值
            affine: False  # 是否使用仿射变换，布尔值
            subtract_last: False  # 是否减去最后一个值，布尔值
            decomposition: False  # 是否使用时间序列分解，布尔值
            kernel_size: 3  # 卷积核大小，范围[3-7]
            patch_len: 5  # patch长度，范围[3-10]
            stride: 2  # patch步长，范围[1-5]
            padding_patch: False  # 是否对patch进行padding，布尔值
            verbose: False  # 是否打印详细信息，布尔值
            GPU: 2  # 使用的GPU编号，范围[0-N]
            n_jobs: 20  # 数据加载的并行进程数，范围[1-32]
            seed: 2025  # 随机种子，任意整数
    dataset:
        class: PatchTSTDatasetH
        module_path: data_formatters.patchtst_dataset
        kwargs:
            handler:
                class: Alpha158
                module_path: qlib.contrib.data.handler
                kwargs: *data_handler_config
            segments:
                train: [2008-01-01, 2021-12-31]
                valid: [2022-01-01, 2023-12-31]
                test: [2024-01-01, 2025-06-30]
            step_len: 20
    record:
        - class: SignalRecord
          module_path: qlib.workflow.record_temp
          kwargs:
            model: <MODEL>
            dataset: <DATASET>
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs:
            ana_long_short: False
            ann_scaler: 252
        - class: PortAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs:
            config: *port_analysis_config
