qlib_init:
    provider_uri: "/home/v-yuanteli/RD-Agent/git_ignore_folder/quant_data"
    region: cn
market: &market csi500
benchmark: &benchmark SH000905
data_handler_config: &data_handler_config
    start_time: 2008-01-01
    end_time: 2025-06-30
    fit_start_time: 2008-01-01
    fit_end_time: 2021-12-31
    instruments: *market
    infer_processors:
        - class: FilterCol
          kwargs:
              fields_group: feature
              col_list: ["RESI5", "WVMA5", "RSQR5", "KLEN", "RSQR10", "CORR5", "CORD5", "CORR10", 
                            "ROC60", "RESI10", "VSTD5", "RSQR60", "CORR60", "WVMA60", "STD5", 
                            "RSQR20", "CORD60", "CORD10", "CORR20", "KLOW"
                        ]
        - class: RobustZScoreNorm
          kwargs:
              fields_group: feature
              clip_outlier: true
        - class: Fillna
          kwargs:
              fields_group: feature
    learn_processors:
        - class: DropnaLabel
        - class: CSRankNorm
          kwargs:
              fields_group: label
    label: ["Ref($close, -2) / Ref($close, -1) - 1"]
port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal: <PRED>
            topk: 50
            n_drop: 5
    backtest:
        start_time: 2024-01-01
        end_time: 2025-06-30
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: 0.095
            deal_price: close
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5
task:
    model:
        class: iTransformer
        module_path: iTransformer
        kwargs:
            d_feat: 20  # 特征维度，通常设置为输入特征的维度，范围[10-100]
            seq_len: 20  # 输入序列长度，表示使用多少历史数据点，范围[10-100]
            pred_len: 1  # 预测长度，表示预测未来多少个时间点，范围[1-30]
            d_model: 256  # Transformer模型维度，范围[32-512]
            embed: 'timeF'  # 嵌入类型，可选[timeF, fixed, learned]
            freq: 'd'  # 时间频率，可选[d, h, m, s]
            dropout: 0.1  # 模型dropout率，用于防止过拟合，范围[0.0-0.5]
            factor: 1  # 注意力因子，范围[1-5]
            e_layers: 2  # 编码器层数，范围[1-6]
            enc_in: 64  # 编码器输入维度，通常等于d_feat，范围[10-100]
            dec_in: 64  # 解码器输入维度，通常等于d_feat，范围[10-100]
            c_out: 64  # 输出维度，通常等于d_feat，范围[10-100]
            n_heads: 8  # 注意力头数，通常为d_model的因子，范围[2-16]
            d_ff: 1024  # 前馈网络维度，通常为d_model的4倍，范围[128-2048]
            use_amp: False  # 是否使用自动混合精度训练，布尔值
            activation: 'gelu'  # 激活函数，可选[gelu, relu, leakyrelu]
            features: 'MS'  # 特征类型，可选[MS, M, S]
            des: 'Exp'  # 实验描述，字符串
            channel_independence: False  # 是否使用通道独立性，布尔值
            inverse: False  # 是否使用逆变换，布尔值
            class_strategy: 'projection'  # 分类策略，可选[projection, token]
            output_attention: True  # 是否输出注意力权重，布尔值
            use_norm: True  # 是否使用归一化，布尔值
            itr: 2  # 迭代次数，范围[1-5]
            train_epochs: 10  # 训练轮数，范围[10-100]
            early_stop: 5  # 早停轮数，当验证集性能不再提升时停止训练，范围[3-10]
            lr: 1e-3  # 学习率，范围[0.00001-0.001]
            batch_size: 800  # 批次大小，根据GPU内存调整，范围[32-2048]
            metric: loss  # 评估指标，可选[loss, mse, mae]
            loss: mse  # 损失函数，可选[mse, mae]
            num_workers: 20  # 数据加载的并行进程数，范围[1-32]
            GPU: 0  # 使用的GPU编号，范围[0-N]
    dataset:
        class: InformerDatasetH
        module_path: data_formatters.informer_dataset
        kwargs:
            handler:
                class: Alpha158
                module_path: qlib.contrib.data.handler
                kwargs: *data_handler_config
            segments:
                train: [2008-01-01, 2021-12-31]
                valid: [2022-01-01, 2023-12-31]
                test: [2024-01-01, 2025-06-30]
            step_len: 21
    record: 
        - class: SignalRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            model: <MODEL>
            dataset: <DATASET>
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            ana_long_short: False
            ann_scaler: 252
        - class: PortAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            config: *port_analysis_config
